server:
  port: 3000

hotswap:
  agent:
    livereload:
      watch-base-dirs:
        - "playground"

spring:
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: false
    restart:
      enabled: true
      poll-interval: 200ms
      quiet-period: 150ms
